# Generated by Django 3.2 on 2021-10-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('print', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=100)),
                ('releasedate', models.CharField(max_length=100)),
                ('certification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatreName', models.CharField(max_length=100)),
                ('time1', models.CharField(max_length=100)),
                ('time2', models.CharField(max_length=100)),
                ('time3', models.CharField(max_length=100)),
                ('time4', models.CharField(max_length=100)),
                ('time5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
