# Generated by Django 3.2 on 2021-10-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0006_auto_20211018_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TheatreSeats',
        ),
    ]
