# Generated by Django 3.2 on 2021-10-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0007_delete_theatreseats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
