# Generated by Django 3.2 on 2021-10-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0008_auto_20211019_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='CastCrew',
            new_name='Cast',
        ),
    ]
