# Generated by Django 3.2 on 2021-10-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0010_auto_20211019_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kirthika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(max_length=20)),
                ('B', models.CharField(max_length=20)),
                ('C', models.CharField(max_length=20)),
                ('D', models.CharField(max_length=20)),
                ('E', models.CharField(max_length=20)),
                ('F', models.CharField(max_length=20)),
                ('G', models.CharField(max_length=20)),
                ('H', models.CharField(max_length=20)),
                ('I', models.CharField(max_length=20)),
                ('J', models.CharField(max_length=20)),
                ('K', models.CharField(max_length=20)),
                ('L', models.CharField(max_length=20)),
                ('M', models.CharField(max_length=20)),
                ('N', models.CharField(max_length=20)),
            ],
        ),
    ]
