# Generated by Django 3.2 on 2021-10-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0011_kirthika'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kirthika',
            name='A',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='B',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='C',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='D',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='E',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='F',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='G',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='H',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='I',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='J',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='K',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='L',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='M',
        ),
        migrations.RemoveField(
            model_name='kirthika',
            name='N',
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat1',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat10',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat11',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat12',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat13',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat14',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat15',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat16',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat17',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat18',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat19',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat2',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat20',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat3',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat4',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat5',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat6',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat7',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='rowId',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
