# Generated by Django 3.2 on 2021-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0012_auto_20211019_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketId', models.CharField(max_length=100)),
                ('theatreName', models.CharField(max_length=100)),
                ('tickets', models.TextField()),
                ('ticketType', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat8',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirthika',
            name='Seat9',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
