# Generated by Django 3.2 on 2021-10-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0013_auto_20211027_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='price',
            new_name='movieName',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='tickets',
            new_name='seats',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticketType',
        ),
        migrations.AddField(
            model_name='ticket',
            name='confee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='subtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='totalTickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
