# Generated by Django 3.2 on 2021-10-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0014_auto_20211030_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cardno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ticketId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
