# Generated by Django 3.2 on 2021-11-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0016_tickettemporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
